org.gradle.jvmargs  = -Xmx3G

#Fabric properties
minecraft_version=1.21.1
yarn_mappings=1.21.1+build.3
loader_version=0.16.9
#Mod properties
mod_version         = 1.4.9
maven_group         = fr.lebon
archives_base_name  = lazypathways

#Dependencies
fabric_api_version=0.116.6+1.21.1
mod_config=15.0.130
mod_menu=11.0.1
